# Generated by Django 6.0.6 on 2026-06-17 00:53
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0002_alter_post_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE TABLE IF NOT EXISTS likes (id bigserial PRIMARY KEY, created_at timestamp with time zone NOT NULL, post_id integer NOT NULL REFERENCES posts_post(id) ON DELETE CASCADE, user_id integer NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE, UNIQUE (user_id, post_id));",
            reverse_sql="DROP TABLE IF EXISTS likes;",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Like',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'likes',
                        'unique_together': {('user', 'post')},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
