# Generated by Django 6.0.6 on 2026-06-12 06:32
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.RunSQL(
            sql="CREATE TABLE IF NOT EXISTS users (id bigserial PRIMARY KEY, password varchar(128) NOT NULL, last_login timestamp with time zone, email varchar(254) NOT NULL UNIQUE, nickname varchar(10) NOT NULL, profile varchar(100) NOT NULL, belonging text NOT NULL, role varchar(15) NOT NULL);",
            reverse_sql="DROP TABLE IF EXISTS users;",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CustomUser',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('password', models.CharField(max_length=128, verbose_name='password')),
                        ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                        ('email', models.EmailField(max_length=254, unique=True)),
                        ('nickname', models.CharField(max_length=10)),
                        ('profile', models.CharField(max_length=100)),
                        ('belonging', models.TextField()),
                        ('role', models.CharField(max_length=15)),
                    ],
                    options={
                        'db_table': 'users',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
