# Generated by Django 5.2.15 on 2026-06-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='belonging',
            field=models.CharField(choices=[('engineering', 'エンジニアリング部'), ('sales', '営業部'), ('marketing', 'マーケティング部'), ('hr', '人事部'), ('finance', '経理部')], max_length=100),
        ),
    ]
