# Generated by Django 6.0.6 on 2026-06-17 00:53
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('posts', '0003_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE TABLE IF NOT EXISTS comments (id bigserial PRIMARY KEY, text text NOT NULL, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL, post_id integer NOT NULL REFERENCES posts_post(id) ON DELETE CASCADE, user_id integer NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE);",
            reverse_sql="DROP TABLE IF EXISTS comments;",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Comment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('text', models.TextField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'comments',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]