# Generated by Django 6.0.6 on 2026-06-16 06:24
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('comments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE TABLE IF NOT EXISTS notifications (id bigserial PRIMARY KEY, read_at timestamp with time zone, created_at timestamp with time zone NOT NULL, comment_id integer NOT NULL REFERENCES comments(id) ON DELETE CASCADE, user_id integer NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE);",
            reverse_sql="DROP TABLE IF EXISTS notifications;",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Notification',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('read_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comments.comment')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'notifications',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]